name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create archive
        run: |
          tar -czf LinuxMidnight-icon-theme.tar.gz .

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: LinuxMidnight-icon-theme
          path: LinuxMidnight-icon-theme.tar.gz
